####################################
# Police VS Terrorists Config File #
####################################
message: Welcome to Police VS Terrorists!

# when will the game auto-start?
auto-start-players: 2

# Mysql connection for hive and resetting
sql:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database: 'PvT'
  prefix: 'pvt_'
  server-prefix : '_one'
  
# whitelist for block breaking and placing ingame. 
block:
  place:
    whitelist:
    - 20
    - 102
  break:
    whitelist:
    - 59
    - 141
    - 142