main: uk.co.shadycast.shadycontroller.ShadyController
name: Shady Controller
version: 1.0
commands:
  Ban:
  Rank:
  Gamemode:
  Kick:
  ?:
  help:
  me:
  pl:
  plugin:
  plugins:
  stop:
  reload:
  rl: