main: uk.co.shadycast.shadycontroller.ShadyController
name: Shady Controller
version: 1.0
load: STARTUP
loadbefore: [Paintball,Shady Hub, Claim]
commands:
  Ban:
  Rank:
  Kick:
  ?:
  help:
  me:
  pl:
  plugins: